server:
  port: 8074

# 本地模拟
yim:
  route:
    login:
      url: http://localhost:8880/login
    chat:
      url: http://localhost:8880/chat
    logout:
      url: http://localhost:8880/logout

  #客户端唯一ID
  user:
    id: 1001
    username: yzecho

#  callback:
#    thread:
#      queue:
#        size: 2 #回调线程队列大小
#      pool:
#        size: 2 #回调线程池大小