server:
  port: 8072

# 本地模拟
yim:
  route:
    login:
      url: http://localhost:8880/login
    chat:
      url: http://localhost:8880/chat
    private:
      url: http://localhost:8880/privateRoute
    logout:
      url: http://localhost:8880/logout
    online:
      url: http://localhost:8880/onlineUser

  #客户端唯一ID
  user:
    id: 1002
    username: user2

#  callback:
#    thread:
#      queue:
#        size: 2 #回调线程队列大小
#      pool:
#        size: 2 #回调线程池大小