server:
  port: 8880


yim:
  zookeeper:
    switch: true
    address: 127.0.0.1:2181
    root: /yimroute

  route:
    wayLoop: io.yzecho.yimcommon.algorithm.loop.LoopHandler #路由策略 轮询
    wayRandom: io.yzecho.yimcommon.algorithm.random.Rouler #路由策略 随机


# Redis配置
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-active: 100 # 连接池最大连接数(使用负值表示没有限制) 默认为8
        max-idle: 100 # 连接池中的最大空闲连接 默认为8
        max-wait: 1000 # 连接池最大阻塞等待时间(使用负值表示没有限制) 默认为-1
        min-idle: 10 # 连接池中的最小空闲连接 默认为0
