spring:
  application:
    name: yim-server
server:
  port: 8084

yim:
  server:
    port: 8094

  zookeeper:
    switch: true
    address: http://localhost:2181
    root: /yimroute

    route:
      logoutUrl: http://localhost:8880/logout

#  etcd:
#    address: http://localhost:2181
#    root: /yimroute
#    route:
#      logoutUrl: http://localhost:8880/logout

